### ISSUE TITLE
[hr_experience] Perbaikan layout form view_academic_form

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/hr#1]
View yang harus diubah:
1. view_academic_form
2. view_professional_form
3. view_certificate_form

Acceptance criteria:
1. Layout form menggunakan group sehingga semua label field muncul

**Comment by andhit-r** [comment]
@azmimr67 bisa bantu untuk menentukan layoutnya?

**Comment by azmimr67** [comment]
Mohon informasi apakah fieldnya tetap atau ditambah

**Comment by andhit-r** [comment]
Tetap

On Sun, Jan 31, 2016 at 8:27 PM, azmimr67 notifications@github.com wrote:

> Mohon informasi apakah fieldnya tetap atau ditambah
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-synergy/hr/issues/1#issuecomment-177502257.

## 

[image: --]

Andhitia Rama
[image: https://]about.me/andhitia.r
https://about.me/andhitia.r?promo=email_sig

**Comment by azmimr67** [comment]
Ada yang bisa kasih info gak.
Field certification number di view_certificate_form itu kalau di view_academic_form field apa?

**Comment by andhit-r** [comment]
@azmimr67 tidak ada field **certification_number** pada **view_academic_form**

**Comment by andhit-r** [comment]
Sebagai info berikut link untuk:
- hr.curriculum : https://github.com/open-synergy/hr/blob/8.0/hr_experience/models/hr_curriculum.py
- hr.certification: https://github.com/open-synergy/hr/blob/8.0/hr_experience/models/hr_certification.py
- hr.academic: https://github.com/open-synergy/hr/blob/8.0/hr_experience/models/hr_academic.py

hr.certification dan hr.academic diinherit dari hr.curriculum

**Comment by andhit-r** [comment]
PR https://github.com/OCA/hr/pull/212
