### ISSUE TITLE
hr_holidays_legal_leave

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/hr#11]
@azmimr67 mohon bantuannya review modul ini. Bukan kita yang buat, tapi akan sangat berguna. PRnya https://github.com/OCA/hr/pull/211. Thanks

**Comment by azmimr67** [comment]
@andhit-r saya agak bingung dengan penggunaan sesudahnya.
Maksud saya adalah saat penggunaan di allocate leave, pada menu ini tidak disebutkan alokasi leave ini berlaku untuk periode kapan. Makusdnya untuk cuti tahunan biasanya sudah ditentukan periodenya. Misalkan cuti tahunan 2017 adalah 1 jan 2017 sd 31 des 2017 alokasinya sebanyak 12 hari
Artinya jika kita tetapkan legal leaves adalah cuti tahunan. 
Maka setiap tahun kita harus mengalokasikan cuti tsb setiap tahun.

Saya juga agak bingung dengan penggunaan jenis cuti.
Sebagai contoh cuti melahirkan
Cuti melahirkan diberikan sebanyak 45 hari per kelahiran.
Bagaimana cara mendefinisikannya?
Sebab jika karyawan melahirkan anak kedua dan sudah mengambil cuti untuk kelahiran anak pertama selama 45 hari, berarti dia tidak bisa mengambil cuti kelahiran lagi.

Intinya untuk issue ini secara fungsi untuk menentukan annual leave sdh ok, tapi secara penggunaan sangat tidak ok.
Jadi saya bingung mau komentarnya.
Mohon advise
