### ISSUE TITLE
hr_contract_state

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/hr#2]
@azmimr67 @mikevhe18 kaya nya modul ini kudu diprioritaskan. Modul ini menambahkan status dan workflow pada kontrak. Sebab kemarin sudah ada pertanyaan mengenai status kontrak, bagaimana cara taunya kontrak yg sedang berjalan atau yg sudah berakhir.

**Comment by andhit-r** [comment]
Belum ada yg mulai migrate juga soalnya di komunitas

**Comment by mikevhe18** [comment]
@andhit-r oke mas kalau memang dibutuhkan. Tapi untuk masalah migrate harus ada prosedurnya gak?

**Comment by andhit-r** [comment]
@azmimr67 mungkin fitur ini bisa cb dilihat di runbot oca. Adanya di branch 7.0

**Comment by andhit-r** [comment]
@mikevhe18 prosedur migrate lihat di https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8.0
