### ISSUE TITLE
hr_expense_product_policy

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/hr#27]
Modul ini akan mewajibkan pengisian product pada Expense sesuai dengan isian employee.

Dependensi: hr_expense

TODO:
[ ] Menambahkan field required_expense_product pada hr.employee
[ ] Menambahkan field required_expense_product pada form hr.employee (lihat screenshot di bawah)
[ ] Menambahkan mekanisme agar ketika pembuatan/pengeditan hr.expense odoo mewajibkan/tidak mewajibkan pengisian produk pada tiap barisnya. Wajib atau tidaknya tergantung pada field require_expense_product
## Posisi Field required_expense_product Pada Form hr.employee

![selection_004](https://cloud.githubusercontent.com/assets/1947376/15004907/4bb7cc9a-11e7-11e6-8749-fa2eff29bffa.png)

PR: https://github.com/OCA/hr/pull/243

**Comment by andhit-r** [comment]
@mikevhe18 kerjain ini juga yah

**Comment by andhit-r** [comment]
Analytic accoutnya udah gw buat. hr_expense_required_product_by_employee

**Comment by mikevhe18** [comment]
@andhit-r Mas, itu view employee yang diatas bukan view standar ya ?

**Comment by andhit-r** [comment]
Bukan. Pokoknya lo tambahinnya di bwh field active

**Comment by andhit-r** [comment]
@mikevhe18 ini contohnya https://github.com/odoomrp/odoomrp-wip/tree/8.0/purchase_order_allowed_product

**Comment by mikevhe18** [comment]
@andhit-r itu khan untuk domain mas, gak bisa dipake untuk attrs. Gue udah nemu caranya pake modifiers, yg belum tau caranya baca xpath dari line_ids/tree.
