### ISSUE TITLE
hr_infraction

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/hr#5]

**Comment by andhit-r** [comment]
@azmimr67 ini dah di PR. Tolong dilihat yah. Runbotnya ada di http://runbot.odoo-community.org/runbot/build/3143335. PR nya ada di https://github.com/OCA/hr/pull/207

**Comment by azmimr67** [comment]
@andhit-r bisa dijelaskan lebih detail mengenai issue ini? Saya tidak tahu menu dan bagian mana yang harus saya review

**Comment by azmimr67** [comment]
@andhit-r saran dari saya diperjelas siapa yang harus mengconfirm, approve dan valid
Sepengetahuan saya untuk proses seperti ini ada user yang request, biasanya adalah head dep.
Namun pada kenyataannya bisa saja yang mengcreate data bukan head dep.
Biasanya Head Dep akan mengconfirm request ini dan pada proses ini head dep bisa mengisi category dan warning (namun ini bukan final) tapi bisa juga kosong.
Pada saat approve biasanya ini adalah bagian pekerjaan HR tapi tergantung dari kebijaksanaan perusahaan. Maka biasanya sistim  mencatat user siapa yang melakukan approve dan biasanya user tsb akan mencantumkan alasan serta hasil diskusi dengan karyawan akan request tsb dan kemudian merubah isi category dan warning.
Jika sudah terjadi kesepakatan antara request, employee dan yang user melakukan approve maka action ini bisa dimark sebagai valid dan biasanya ada tgl valid yang merupakan tanggal mulai berlaku.

**Comment by andhit-r** [comment]
@azmimr67 flow yang saya buat memang sudah seperti itu. Untuk penjelasan how-to-nya bisa dilihat di https://github.com/andhit-r/hr/blob/5fff3c136a1729ce51a162c20b61dde7b2f385b9/hr_infraction/README.rst. Sepertinya harus dilengkapi lagi supaya lebih jelas.

**Comment by andhit-r** [comment]
Sekarang sedang direview juga di OCA. Lihat link di atas untuk link ke PR nya
