### ISSUE TITLE
hr_employee_id

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/hr#8]
cc @azmimr67 @mikevhe18

**Comment by andhit-r** [comment]
Runbot: http://runbot.odoo-community.org/runbot/build/3143189
PR: https://github.com/OCA/hr/pull/205

**Comment by azmimr67** [comment]
@andhit-r can you describe what is the detail of the issue?

**Comment by andhit-r** [comment]
Tinggal di test di runbot  http://runbot.odoo-community.org/runbot/build/3143189. Kalau oke kasih :+1: di PR nya. Penjelasan mengenai fungsi modul selalu lihat di README
